# Generated by Django 3.2.25 on 2025-05-31 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass_app', '0002_auto_20250531_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityguard',
            name='date_of_join',
        ),
        migrations.RemoveField(
            model_name='securityguard',
            name='emp_name',
        ),
    ]
